services:
  web:
    build: .
    command: gunicorn django_project.wsgi:application --bind 0.0.0.0:8000 --timeout 300 --workers 3 --preload

    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
volumes:
  postgres_data: