# Generated by Django 5.0.12 on 2025-03-06 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.CharField(max_length=100)),
                ('TransactionId', models.CharField(max_length=100)),
                ('TransactionTime', models.CharField(max_length=500)),
                ('ItemCode', models.CharField(max_length=100)),
                ('ItemDescription', models.TextField()),
                ('NumberOfItemsPurchased', models.IntegerField()),
                ('CostPerItem', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Country', models.CharField(max_length=100)),
            ],
        ),
    ]
