# Generated by Django 5.0.12 on 2025-03-09 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='document',
            field=models.FileField(default='default_value.xlsx', upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
