# Generated by Django 5.1.7 on 2025-04-05 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='nextitemprediction',
            name='unique_user_id_and_predicted_at',
        ),
    ]
