# Generated by Django 5.0.12 on 2025-03-09 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0002_transaction_document_transaction_uploaded_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='document',
        ),
    ]
