# Generated by Django 5.1.7 on 2025-04-25 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0003_alter_itemsaleforecast_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcustomerrecommendation',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='ai_models.customerdetail', to_field='UserId'),
        ),
        migrations.AlterModelTable(
            name='itemsaleforecast',
            table='ai_models_itemsaleforecast',
        ),
    ]
