# Generated by Django 5.0.12 on 2025-03-10 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0003_remove_transaction_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='uploaded_at',
        ),
    ]
