# Generated by Django 5.0.12 on 2025-03-10 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0004_remove_transaction_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
