# Generated by Django 5.0.12 on 2025-03-10 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0005_transaction_uploaded_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='sale_forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ds', models.CharField(max_length=500)),
                ('prediction', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prediction_lower', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prediction_upper', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
