# Generated by Django 5.1.7 on 2025-04-25 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0005_alter_newcustomerrecommendation_user'),
    ]

    operations = [
    ]
