# Generated by Django 5.1.7 on 2025-05-29 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0006_auto_20250425_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nextitemprediction',
            name='UserId',
            field=models.ForeignKey(db_column='UserId', on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='ai_models.customerdetail', to_field='UserId'),
        ),
    ]
