# Generated by Django 5.0.12 on 2025-03-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0006_sale_forecast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='uploaded_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
