# Generated by Django 5.0.12 on 2025-03-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0007_alter_transaction_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale_forecast',
            name='uploaded_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
