# Generated by Django 5.1.7 on 2025-05-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0007_alter_nextitemprediction_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nextitemprediction',
            name='UserId',
            field=models.CharField(max_length=100),
        ),
    ]
