# Generated by Django 5.0.12 on 2025-03-15 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0008_sale_forecast_uploaded_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='NextItemPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.IntegerField()),
                ('PredictedItemCode', models.IntegerField()),
                ('Probability', models.FloatField()),
                ('PredictedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
