# Generated by Django 5.1.7 on 2025-06-24 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0008_alter_nextitemprediction_userid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemsaleforecast',
            options={},
        ),
    ]
