# Generated by Django 5.0.12 on 2025-03-15 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0009_nextitemprediction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nextitemprediction',
            name='PredictedItemCode',
            field=models.CharField(max_length=100),
        ),
    ]
