# Generated by Django 5.0.12 on 2025-03-15 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0010_alter_nextitemprediction_predicteditemcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='upload_batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ai_models.uploadbatch'),
        ),
    ]
