# Generated by Django 5.0.12 on 2025-03-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0011_uploadbatch_transaction_upload_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemCode', models.CharField(max_length=50, unique=True)),
                ('ItemDescription', models.CharField(max_length=200)),
                ('CostPerItem', models.DecimalField(decimal_places=2, max_digits=10)),
                ('uploaded_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
