# Generated by Django 5.0.12 on 2025-03-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0012_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='nextitemprediction',
            name='PredictedItemCost',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='nextitemprediction',
            name='PredictedItemDescription',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
