# Generated by Django 5.0.12 on 2025-03-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0013_nextitemprediction_predicteditemcost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nextitemprediction',
            name='UserId',
            field=models.CharField(max_length=100),
        ),
    ]
