# Generated by Django 5.0.12 on 2025-03-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0014_alter_nextitemprediction_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('existing_customer', models.CharField(max_length=3)),
                ('country', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('income', models.IntegerField()),
                ('occupation', models.CharField(max_length=100)),
                ('education_level', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
