# Generated by Django 5.0.12 on 2025-03-16 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0015_customerdetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerDetails',
            new_name='CustomerDetail',
        ),
    ]
