# Generated by Django 5.0.12 on 2025-03-16 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0016_rename_customerdetails_customerdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerdetail',
            old_name='user_id',
            new_name='userid',
        ),
    ]
