# Generated by Django 5.0.12 on 2025-03-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0017_rename_user_id_customerdetail_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdetail',
            name='userid',
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='UserId',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
