# Generated by Django 5.0.12 on 2025-03-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0018_remove_customerdetail_userid_customerdetail_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetail',
            name='UserId',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
