# Generated by Django 5.0.12 on 2025-03-16 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0019_alter_customerdetail_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nextitemprediction',
            name='UserId',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='UserId',
        ),
        migrations.AddField(
            model_name='nextitemprediction',
            name='legacy_user_id',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nextitemprediction',
            name='user',
            field=models.ForeignKey(blank=True, db_column='UserId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='ai_models.customerdetail'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='legacy_user_id',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(blank=True, db_column='UserId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='ai_models.customerdetail'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='TransactionId',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
