# Generated by Django 5.0.12 on 2025-03-16 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0020_remove_nextitemprediction_userid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nextitemprediction',
            name='legacy_user_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='legacy_user_id',
        ),
        migrations.AlterField(
            model_name='nextitemprediction',
            name='user',
            field=models.ForeignKey(db_column='UserId', on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='ai_models.customerdetail'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(db_column='UserId', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='ai_models.customerdetail'),
        ),
    ]
