# Generated by Django 5.0.12 on 2025-03-16 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0021_remove_nextitemprediction_legacy_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetail',
            name='UserId',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
