# Generated by Django 5.0.12 on 2025-03-17 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0024_remove_transaction_upload_batch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='TransactionId',
            field=models.CharField(max_length=100),
        ),
    ]
