# Generated by Django 5.0.12 on 2025-03-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0025_alter_transaction_transactionid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nextitemprediction',
            name='user',
        ),
        migrations.AddField(
            model_name='nextitemprediction',
            name='UserId',
            field=models.CharField(default=1111, max_length=100),
            preserve_default=False,
        ),
    ]
