# Generated by Django 5.0.12 on 2025-03-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0026_remove_nextitemprediction_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetail',
            name='existing_customer',
            field=models.CharField(max_length=10),
        ),
    ]
