# Generated by Django 5.0.12 on 2025-03-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0028_alter_customerdetail_existing_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetail',
            name='existing_customer',
            field=models.BooleanField(),
        ),
    ]
