# Generated by Django 5.1.7 on 2025-03-19 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0029_alter_customerdetail_existing_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='TransactionId',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
