# Generated by Django 5.1.7 on 2025-03-19 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0030_alter_transaction_transactionid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='TransactionId',
            field=models.CharField(max_length=255),
        ),
    ]
