# Generated by Django 5.1.7 on 2025-03-20 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0031_alter_transaction_transactionid'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='nextitemprediction',
            constraint=models.UniqueConstraint(fields=('UserId', 'PredictedAt'), name='unique_user_id_and_predicted_at'),
        ),
    ]
