# Generated by Django 5.0.12 on 2025-03-04 02:32

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_description', models.CharField(max_length=2000)),
                ('product_name', models.CharField(max_length=2000)),
                ('image', models.ImageField(default=products.models.default_image_path, upload_to='product_images/')),
            ],
        ),
    ]
